### ISSUE TITLE
Cannot install/find OpenSSL on OSX

### ISSUE THREAD

**Issue by jakehsiao** [udacity/CarND-PID-Control-Project#2]
To install OpenSSL, I tried
```
brew install openssl
```
And it returns
```
Warning: openssl is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
```
Then I tried
```
brew install --force openssl
```
And it returns
```
Warning: openssl-1.0.2k already installed, it's just not linked.
```
Then I tried to link with force
```
brew link --force
```
Then it returns
```
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```
And I don't know what to do next.

When I run "install-mac.sh", it failed.

```
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindOpenSSL.cmake:385 (find_package_handle_standard_args)
  CMakeLists.txt:8 (find_package)
```

**Comment by olegleyz** [comment]
Hi @jakehsiao,
CMake can not find your OpenSSL lib, you have to manually tell him where is it, using the option -D.
1. Find the path to OpenSSL locally. For me its: `/usr/local/Cellar/openssl/1.0.2k`. Make sure you can see hidden files.
2. in install-mac.sh change `cmake ..` to `cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2k -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2k/lib ..  `

**Comment by philbort** [comment]
@olegleyz 's solution works for me. This should be a common issue for all Mac users which needs to be addressed.

**Comment by jakehsiao** [comment]
Thanks, @olegleyz 's solution works for me too.

**Comment by mkriventsev** [comment]
That's worked for me too. @olegleyz , Thank you

**Comment by ramzerof** [comment]
fro me worked like this passing variables on runtime: 
cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib

**Comment by mvirgo** [comment]
Looks like we mostly fixed this through cade8d1 and 7e31b50, so closing this out.

**Comment by wu-yy** [comment]
year, when I compile the c++ GRPC, I use these command:
`cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2r -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2r/lib ../..`

**Comment by patrickelectric** [comment]
You can also set the env variables in your bash_profile or zshrc
```
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by dvhwgumby** [comment]
Unless you need to be pinned to a specific version you will find it easier to use the opt/ path which has a symlink to the latest version:

-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
-DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib

**Comment by marimeireles** [comment]
Hi @mvirgo it wasn't fixed for me, I had to add Patrick's solution to my .rc file.
If you think it's relevant I can open a new issue with more information (or provide it here).

**Comment by bengkeong97** [comment]
> Hi @jakehsiao,
> CMake can not find your OpenSSL lib, you have to manually tell him where is it, using the option -D.
> 
> 1. Find the path to OpenSSL locally. For me its: `/usr/local/Cellar/openssl/1.0.2k`. Make sure you can see hidden files.
> 2. in install-mac.sh change `cmake ..` to `cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2k -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2k/lib ..`

Where can in locate install-mac.sh?

**Comment by youshanli** [comment]
> 嗨@jakehsiao， CMake 找不到您的 OpenSSL 库，您必须使用选项 -D 手动告诉他在哪里。
> 
> 1. 在本地找到 OpenSSL 的路径。对我：`/usr/local/Cellar/openssl/1.0.2k`。确保您可以看到隐藏文件。
> 2. 在 install-mac.sh 中更改`cmake ..`为`cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2k -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2k/lib ..  `

My local path is different from yours, but I don't know which one is its path and what suffix is it? thank you！
