### ISSUE TITLE
output uWS headers

### ISSUE THREAD

**Issue by Horki** [udacity/CarND-PID-Control-Project#24]
@domluna @baumanab @mvirgo @swwelch @DavidObando @HTuennermann @citlaligm 
How to output all of `uWS` request's headers?

I want something close enough to this example
```
  h.onConnection([&h](uWS::WebSocket<uWS::SERVER> ws, uWS::HttpRequest req) {
    // TODO: output request's path
    std::cout << "Request's path << req.getPath() << std::endl; // how to?
    std::cout << "Output all request's headers: ";
    std::for_each(req.headers.begin(), req.headers.end(). [] (std::string h) { std::cout << h << std::endl; });
    std::cout << "Connected!!!\n";
  });

```

**Comment by UAnjali** [comment]
Hi @Horki,
Apologies for the extremely delayed response. Please let us know if you need assistance with this issue. 
We suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. 
Thanks

**Comment by Horki** [comment]
@UAnjali LOL
