### ISSUE TITLE
Windows bug

### ISSUE THREAD

**Issue by anthony-chaudhary** [udacity/CarND-PID-Control-Project#4]
Hello,

I'm having trouble getting the compiled version to work on my machine
Please see:
https://github.com/udacity/CarND-PID-Control-Project/pull/3
https://discussions.udacity.com/t/project-build-for-windows-users/245846/11

Any suggestions or ideas? I'm just trying to get the base code provided to work.

Anthony

**Comment by anthony-chaudhary** [comment]
Please see https://github.com/fera0013/CarND-PID-Control-Project  his base build loads using cmake lists for me

**Comment by DavidObando** [comment]
Windows setup instructions described in detail in the [slack channel](https://carnd.slack.com/archives/C4Z4GFX0X/p1493794760012703).

(BTW, what's up with Udacity ignoring Windows-based students completely these days?)

**Comment by mvirgo** [comment]
I've added the setup instructions previously posted to Slack through 21048f5. I also believe our earlier addition of workspaces into the classroom should also alleviate most of this, since you can work on the project within the classroom environment. Thanks for bringing to our attention!
